name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: tranquil430
          template: classic
          base: header, activity, community, repositories, metadata
          # This enables private commit tracking
          config_timezone: Asia/Manila
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
